### ISSUE TITLE
Can EMIRGE work with FASTA files?

### ISSUE THREAD

**Issue by audy** [csmiller/EMIRGE#16]
I'd like to use pre-trimmed FASTA files with EMIRGE. I believe this is supported in Bowtie. Is it possible to add this feature?

**Comment by epruesse** [comment]
Hi Audy,

we are not planning to add that feature. Emirge uses the read qualities in its EM algorithm, not having them looses some information. You could just convert your FASTA to FASTQ with fake quality values.

Elmar

**Comment by audy** [comment]
ty
