### ISSUE TITLE
Use setuptools to simplify installation

### ISSUE THREAD

**Issue by JMBattista** [csmiller/EMIRGE#17]
Switch to importing setuptools instead of disutils.core and add 

install_requires=[
  "BioPython",
  "Cython",
  "pysam",
  "scipy"
],

so the setup area. The installation will automatically ensure that these dependencies are installed on the machine as part of the install.

http://stackoverflow.com/questions/9810603/adding-install-requires-to-setup-py-when-making-a-python-package

**Comment by epruesse** [comment]
fixed in development branch
