### ISSUE TITLE
EMIRGE dependencies

### ISSUE THREAD

**Issue by aslett1** [csmiller/EMIRGE#18]
Hi,

Is EMIRGE still maintained and is it being tested with newer versions of usearch, bowtie and samtools as well as the required python packages? I'm trying to install it centrally on our cluster but hitting segmentation faults:

/tmp/1453995841.5729613: line 8: 19013 Segmentation fault      emirge.py /lustre/scratch108/pathogen/maa/emirge/ -1 18512_8#4_1.fastq.gz -f ../silva/filtered_SILVA_123_SSURef_Nr99_tax_silva.fasta -b ../silva/filtered_SILVA_123_SSURef_Nr99_tax_silva.fasta -l 75 --phred33

Thanks,

Martin

**Comment by JMBattista** [comment]
I can't speak to newer versions but I wrote a setup guide that lists the exact versions I used in the past: http://jmbattista.com/2014/09/03/getting-started-emirge-on-starcluster/#more-9

Also make sure you are using 64 bit Python/Usearch.

**Comment by aslett1** [comment]
Thanks! That may be useful...

On Wed, 10 Feb 2016, John Battista wrote:

> 
> I can't speak to newer versions but I wrote a setup guide that lists the exact versions I used in the past:
> http://jmbattista.com/2014/09/03/getting-started-emirge-on-starcluster/#more-9
> 
> Also make sure you are using 64 bit Python/Usearch.
> 
> —
> Reply to this email directly or view it on GitHub.[AAwjN-CGJ1gnRgJ53NTtftyjqYpa6R4Jks5pi0QhgaJpZM4HXOG4.gif]
> 
> 
>


-- 
 The Wellcome Trust Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.

**Comment by epruesse** [comment]
@aslett1: Yes, Emirge is still being maintained. We are just very busy getting Emirge 2 ready, so the stable hasn't been getting much TLC lately. Emirge 2 will have support for Bowtie2 and Vsearch, and most likely also for BBMap and BWA.
