### ISSUE TITLE
EMIRGE method choice

### ISSUE THREAD

**Issue by domenico-simone** [csmiller/EMIRGE#28]
Hello,

I would like to try EMIRGE on metatranscriptome reads. Indeed I have already sorted the putative SSU reads out with cmsearch. Would you suggest using the normal EMIRGE version or the amplicon variant?

Thanks,
Domenico

**Comment by csmiller** [comment]
I'd recommend the amplicon version for speed, but you might have to restrict the run to a few million reads depending on RAM and patience.   If you try this and have other insights or suggestions, let everyone know here:
[https://groups.google.com/group/emirge-users](https://groups.google.com/group/emirge-users)
Chris
