### ISSUE TITLE
Candidate db file dead link

### ISSUE THREAD

**Issue by ppericard** [csmiller/EMIRGE#29]
The link to download the candidate db file doesnt work anymore.
https://googledrive.com/host/0B7hz7JVEE15dbUtkRmxKVlhtd1U/SSURef_111_candidate_db.fasta.gz

Could you update it, please ?

**Comment by csmiller** [comment]
The master branch on github has just been updated with a new method to download and build a default EMIRGE database.  The new script presents the SILVA license and prompts you to accept it, then
1. downloads the most recent SSU database directly from [SILVA](https://www.arb-silva.de/),
2. filters it by sequence length
3. clusters at 97% sequence identity
4. replaces ambiguous bases with random characters, and
5. creates a bowtie index.

This is back-ported from something @epruesse wrote for EMIRGE2.

Try out this for more options:
`python emirge_makedb.py --help`

Let us know if there are any issues.
Chris
