### ISSUE TITLE
EMIRGE compatible with bowtie v.1+ ?

### ISSUE THREAD

**Issue by jvollme** [csmiller/EMIRGE#33]
Your dependencies state bowtie v. 0.12.7 or v.0.12.8 as dependencies. However bowtie currently is already at version 1.2.0. 
Is there a reason for emirge to require/prefer these old versions of bowtie? Or would the new versions of bowtie work just as well with emirge?

**Comment by epruesse** [comment]
I am not aware of any reason not to go for the newest version, I'd actually recommend doing so.

While the README says that Emirge was _tested_ with the two versions of Bowtie you mention (at the time of original publication, IIRC), it does not intend to imply that EMIRGE won't work with newer versions.

**Comment by cjfields** [comment]
Note issue #36, which indicates that bowtie 1.2.0 doesn't work with EMIRGE
